import { Box } from "@mui/material";

//MetaData for Home page
export const metadata = {
    title: "indoom | Car info",
    description: "Generated by indoom.com",
  };
export default function Carinfo(){
    return(
        <Box sx={{mt: { xs: 4, sm: 5 }, minHeight: '100vh',}}>
        
        </Box>
    )
}