import { Box, Typography } from "@mui/material";
import Swipper from "./home/component/swiper";
import Aboutus from "./home/component/aboutus";
import Whyindoom from "./home/component/whyindoom";
import Findcar from "./home/component/findcar";

//MetaData for Home page
export const metadata = {
  title: "indoom | Home Page",
  description: "Generated by indoom.com",
};
export default function Homepage() {
  return (
    <Box sx={{mt: { xs: 4, sm: 5 }, minHeight: '100vh',}}>
        <Swipper/>
        <Box sx={{px:{xs:4, sm:8 ,md:20, lg:30}, my:10}}>
            <Aboutus/>
        </Box>
        <Whyindoom/>
        <Box sx={{px:{xs:4, sm:8 ,md:20, lg:30}, my:10}}>
          <Findcar/>
        </Box>
    </Box>
  );
}
